//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


declare class Area {
  id: string;
  name: string;
  parentId: string;
  code: string;
  initial: string;

  constructor(args?: { id: string; name: string; parentId: string; code: string; initial: string; });
}

declare class AreaItem {
  provinceId: string;
  provinceName: string;
  cityId: string;
  cityName: string;
  regionId: string;
  regionName: string;

  constructor(args?: { provinceId: string; provinceName: string; cityId: string; cityName: string; regionId: string; regionName: string; });
}

declare class Province {
  id: string;
  name: string;
  pyName: string;

  constructor(args?: { id: string; name: string; pyName: string; });
}

declare class City {
  id: string;
  name: string;
  pyName: string;
  provinceId: string;

  constructor(args?: { id: string; name: string; pyName: string; provinceId: string; });
}

declare class Region {
  id: string;
  name: string;
  cityId: string;

  constructor(args?: { id: string; name: string; cityId: string; });
}

declare class Terminal {
  terminalId: string;
  terminalNo: string;
  terminalName: string;
  networkId: string;
  networkName: string;

  constructor(args?: { terminalId: string; terminalNo: string; terminalName: string; networkId: string; networkName: string; });
}
